export enum AppRoute {
  ROOT = '/',
  ADMIN = '/admin',
  ADMIN_SUBADMIN = '/admin/subadmin',
  ADMIN_DASHBOARD = '/admin/dashboard',
  ADMIN_MEMBERS = '/admin/members',
  ADMIN_DEALS = '/admin/deals',
  SUBADMIN = '/subadmin',
  SUBADMIN_DASHBOARD = '/subadmin/dashboard',
  SUBADMIN_DEALS = '/subadmin/deals',
  SUBADMIN_MEMBERS = '/subadmin/members',
  SUBADMIN_COMMUNICATION = '/subadmin/communications',
  SUBADMIN_SETTINGS = '/subadmin/settings',
  KYC = '/kyc',
  KYC_DASHBOARD = '/kyc/dashboard',
}
